config/routes.rb
NoCms::Admin::Events::Engine.routes.draw do
  resources :locations
  resources :events
end

app/controllers/no_cms/admin/events/application_controller.rb
module NoCms
  module Admin
    module Events
      class ApplicationController < NoCms::Admin::ApplicationController
      end
    end
  end
end

app/controllers/no_cms/admin/events/events_controller.rb
require_dependency "no_cms/admin/events/application_controller"

module NoCms::Admin::Events
  class EventsController < ApplicationController

    before_filter :load_menu_section
    before_filter :load_event, only: [:edit, :update, :destroy]
    before_filter :load_sidebar, only: [:index, :new, :edit]


    def new
      @event = NoCms::Events::Event.new
    end

    def create
      @event = NoCms::Events::Event.new event_params
      if @event.save
        @nocms_logger.info(I18n.t('.no_cms.admin.events.events.create.success', title: @event), true)
        redirect_to edit_event_path(@event)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.events.create.error', title: @event))
        load_sidebar
        render :new
      end
    end

    def edit
      @nocms_logger.add_message :events, I18n.t('.no_cms.admin.events.events.edit.log_messages', title: @event)
    end

    def update
      if @event.update_attributes event_params
        @nocms_logger.info(I18n.t('.no_cms.admin.events.events.update.success', title: @event), true)
        redirect_to edit_event_path(@event)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.events.update.error', title: @event))
        load_sidebar
        render :edit
      end
    end

    def destroy
      if @event.destroy
        @nocms_logger.info(I18n.t('.no_cms.admin.events.events.destroy.success', title: @event), true)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.events.destroy.error', title: @event), true)
      end
      redirect_to events_path
    end

    private

    def load_menu_section
      @current_section = 'events'
    end

    def load_event
      @event = NoCms::Events::Event.friendly.find(params[:id])
    end

    def load_sidebar
      @events = NoCms::Events::Event.all
    end

    def event_params
      event_params = params.require(:event).permit(:title, :slug, :description, :location_id, :starts_at, :ends_at)
    end

  end
end

app/controllers/no_cms/admin/events/locations_controller.rb
require_dependency "no_cms/admin/events/application_controller"

module NoCms::Admin::Events
  class LocationsController < ApplicationController

    before_filter :load_menu_section
    before_filter :load_location, only: [:edit, :update, :destroy]
    before_filter :load_sidebar, only: [:index, :new, :edit]


    def new
      @location = NoCms::Events::Location.new
    end

    def create
      @location = NoCms::Events::Location.new location_params
      if @location.save
        @nocms_logger.info(I18n.t('.no_cms.admin.events.locations.create.success', title: @location), true)
        redirect_to edit_location_path(@location)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.locations.create.error', title: @location))
        load_sidebar
        render :new
      end
    end

    def edit
      @nocms_logger.add_message :events, I18n.t('.no_cms.admin.events.locations.edit.log_messages', title: @location)
    end

    def update
      if @location.update_attributes location_params
        @nocms_logger.info(I18n.t('.no_cms.admin.events.locations.update.success', title: @location), true)
        redirect_to edit_location_path(@location)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.locations.update.error', title: @location))
        load_sidebar
        render :edit
      end
    end

    def destroy
      if @location.destroy
        @nocms_logger.info(I18n.t('.no_cms.admin.events.locations.destroy.success', title: @location), true)
      else
        @nocms_logger.error(I18n.t('.no_cms.admin.events.locations.destroy.error', title: @location), true)
      end
      redirect_to locations_path
    end

    private

    def load_menu_section
      @current_section = 'locations'
    end

    def load_location
      @location = NoCms::Events::Location.find(params[:id])
    end

    def load_sidebar
      @locations = NoCms::Events::Location.all
    end

    def location_params
      location_params = params.require(:location).permit(:name, :description, :lat, :lng)
    end

  end
end

app/helpers/no_cms/admin/events/application_helper.rb
module NoCms
  module Admin
    module Events
      module ApplicationHelper
      end
    end
  end
end

app/helpers/no_cms/admin/events/events_helper.rb
module NoCms
  module Admin
    module Events
      module EventsHelper
        def event_listing_item_classes item, current
          classes = []
          classes << 'current' if current == item
          classes
        end
      end
    end
  end
end

app/helpers/no_cms/admin/events/locations_helper.rb
module NoCms
  module Admin
    module Events
      module LocationsHelper
        def location_listing_item_classes item, current
          classes = []
          classes << 'current' if current == item
          classes
        end
      end
    end
  end
end

app/views/no_cms/admin/events/events/_content_fields.html.erb
<div id="content_fields">
  <div class="row">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="row">
    <%= f.label_with_tooltip :slug, { tooltip: t('.slug_tooltip', base: no_cms_events.events_path)} %>
    <%= f.text_field :slug %>
  </div>

  <div class="row">
    <%= f.label :location_id %>
    <%= f.collection_select :location_id, NoCms::Events::Location.includes(:translations), :id, :name %>
  </div>

  <div class="row">
    <%= f.label_with_tooltip :starts_at, { tooltip: t('.starts_at_tooltip')} %>
    <%= f.datetime_picker :starts_at %>
  </div>

  <div class="row">
    <%= f.label_with_tooltip :ends_at, { tooltip: t('.ends_at_tooltip')} %>
    <%= f.datetime_picker :ends_at %>
  </div>

  <div class="row">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
</div>

app/views/no_cms/admin/events/events/_event_listing.html.erb
<ul>
  <%= yield %>
</ul>

app/views/no_cms/admin/events/events/_event_listing_item.html.erb
<% current ||= nil %>
<li <%= raw "class='#{event_listing_item_classes(event, current).join(' ')}'"%>>
  <%= link_to event.title, edit_event_path(event)%>
  <div class="mo">
    <%= button_to '', event_path(event), method: :delete, class: "ico-mini-delete", title: t('.destroy') %>
  </div>
</li>

app/views/no_cms/admin/events/events/_toolbar_right.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>
<% # We must check that routes are mounted. Otherwise it will get a 404 error %>
<%= link_to t('.visit'), no_cms_events.url_for(@event), target: '_blank', class: "preview btn right" if defined?(no_cms_events) && !@event.new_record?  %>

app/views/no_cms/admin/events/events/edit.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'event_listing_item', collection: @events, as: 'event', layout: 'event_listing', locals: { current: @event } unless @events.blank? %>
<% end %>


<%= no_cms_admin_form_for @event do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/events/events/index.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'event_listing_item', collection: @events, as: 'event', layout: 'event_listing' unless @events.blank? %>
<% end %>

<div class="content">
  <%= render 'no_cms/admin/shared/log_messages' %>
</div>

app/views/no_cms/admin/events/events/new.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'event_listing_item', collection: @events, as: 'event', layout: 'event_listing' unless @events.blank? %>
<% end %>


<%= no_cms_admin_form_for @event do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/events/locations/_content_fields.html.erb
<% content_for :ready_js do %>
  NoCMS.Admin.Map.async_init();
<% end %>

<div id="content_fields">
  <div class="row">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="row">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="row">
    <%= label_tag :address, t('.address') %>
    <%= f.map_field address: { fake: true }, latitude: { field: :lat }, longitude: { field: :lng } %>
  </div>
</div>

app/views/no_cms/admin/events/locations/_location_listing.html.erb
<ul>
  <%= yield %>
</ul>

app/views/no_cms/admin/events/locations/_location_listing_item.html.erb
<% current ||= nil %>
<li <%= raw "class='#{location_listing_item_classes(location, current).join(' ')}'"%>>
  <%= link_to location.name, edit_location_path(location)%>
  <div class="mo">
    <%= button_to '', location_path(location), method: :delete, class: "ico-mini-delete", title: t('.destroy') %>
  </div>
</li>

app/views/no_cms/admin/events/locations/_toolbar_right.html.erb
<%= f.submit t('.submit'), name: :submit, class: "btn right" %>

app/views/no_cms/admin/events/locations/edit.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'location_listing_item', collection: @locations, as: 'location', layout: 'location_listing', locals: { current: @location } unless @locations.blank? %>
<% end %>


<%= no_cms_admin_form_for @location do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>

app/views/no_cms/admin/events/locations/index.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'location_listing_item', collection: @locations, as: 'location', layout: 'location_listing' unless @locations.blank? %>
<% end %>

<div class="content">
  <%= render 'no_cms/admin/shared/log_messages' %>
</div>

app/views/no_cms/admin/events/locations/new.html.erb
<% content_for :second_menu do %>
  <%= render partial: 'location_listing_item', collection: @locations, as: 'location', layout: 'location_listing' unless @locations.blank? %>
<% end %>


<%= no_cms_admin_form_for @location do |f| %>
  <%= render partial: 'no_cms/admin/shared/toolbar', locals: { f: f } %>
  <div class="content">
    <%= render 'no_cms/admin/shared/log_messages' %>
    <%= render 'content_fields', f: f %>
  </div>
<% end %>